language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below